"""
Statistical analysis utilities for the representation-dependent IDS study.

Purpose
-------
This module provides the statistical procedures used to analyse the
Dataset × Representation × Architecture experimental design.

The primary inferential model is a full factorial analysis with:

    Dataset
    Representation
    Architecture
    Run

and the principal interaction of interest:

    Representation × Architecture

A three-way:

    Dataset × Representation × Architecture

interaction is also supported.

The implementation is intentionally based on run-level observations rather
than already-aggregated table values. This preserves the repeated-run
structure described in the manuscript.

The module supports:
    * descriptive statistics
    * mean ± SD
    * confidence intervals for means
    * factorial Type III ANOVA
    * partial eta-squared effect sizes
    * dataset-specific follow-up analysis
    * Representation × Architecture interaction extraction
    * optional pairwise post-hoc comparisons

Important reproducibility note
------------------------------
This file provides the analysis procedures required by the documented
experimental design. It does not claim that any particular historical
statistical output was generated by this reconstructed repository unless the
corresponding run-level result CSV is supplied.

Expected long-format result columns
------------------------------------
At minimum:

    Dataset
    Representation
    Architecture
    Seed

and one or more metric columns, for example:

    Macro_F1
    MCC
    Accuracy
    Brier_Score
    ECE

Column-name aliases used by the available experiment runners are accepted
where practical.

The analysis assumes that each row represents one experimental run for one
Dataset × Representation × Architecture condition.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Iterable, Optional, Sequence

import numpy as np
import pandas as pd


DEFAULT_DATASETS = (
    "CIC-DDoS2019",
    "CICIoT2023",
    "CIC-IoT-DIAD2024",
)

DEFAULT_REPRESENTATIONS = (
    "Flow",
    "Header",
    "Hybrid",
)

DEFAULT_ARCHITECTURES = (
    "LR",
    "RF",
    "XGB",
    "CNN",
    "BiLSTM",
)

DEFAULT_METRICS = (
    "Macro_F1",
    "MCC",
    "Accuracy",
    "Brier_Score",
    "ECE",
)

DEFAULT_SEEDS = tuple(range(2026, 2036))


def _normalise_column_name(name: str) -> str:
    """Normalise a column name for alias matching."""
    return (
        str(name)
        .strip()
        .lower()
        .replace(" ", "_")
        .replace("-", "_")
        .replace("%", "pct")
    )


def find_column(
    dataframe: pd.DataFrame,
    candidates: Sequence[str],
    required: bool = True,
) -> Optional[str]:
    """
    Find a dataframe column using case/format-insensitive aliases.
    """
    normalised = {
        _normalise_column_name(column): column
        for column in dataframe.columns
    }

    for candidate in candidates:
        key = _normalise_column_name(candidate)
        if key in normalised:
            return normalised[key]

    if required:
        raise ValueError(
            "Required column not found. "
            f"Accepted names: {list(candidates)}. "
            f"Available columns: {list(dataframe.columns)}"
        )

    return None


def standardise_result_columns(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """
    Rename common result-column variants to canonical analysis names.

    Canonical names:
        Dataset
        Representation
        Architecture
        Seed
        Macro_F1
        MCC
        Accuracy
        Brier_Score
        ECE
    """
    aliases = {
        "Dataset": (
            "Dataset",
            "dataset",
        ),
        "Representation": (
            "Representation",
            "representation",
            "Rep",
        ),
        "Architecture": (
            "Architecture",
            "architecture",
            "Model",
            "model",
        ),
        "Seed": (
            "Seed",
            "seed",
            "Run",
            "run",
        ),
        "Macro_F1": (
            "Macro_F1",
            "macro_f1",
            "Macro F1",
            "F1_Macro",
        ),
        "MCC": (
            "MCC",
            "mcc",
            "Matthews_Correlation_Coefficient",
        ),
        "Accuracy": (
            "Accuracy",
            "accuracy",
            "ACC",
        ),
        "Brier_Score": (
            "Brier_Score",
            "brier",
            "brier_score",
            "Brier",
        ),
        "ECE": (
            "ECE",
            "ece",
            "Expected_Calibration_Error",
        ),
    }

    rename_map = {}

    for canonical, candidates in aliases.items():
        column = find_column(
            dataframe,
            candidates,
            required=False,
        )

        if column is not None and column != canonical:
            rename_map[column] = canonical

    result = dataframe.rename(
        columns=rename_map
    ).copy()

    find_column(
        result,
        ("Dataset",),
        required=True,
    )
    find_column(
        result,
        ("Representation",),
        required=True,
    )
    find_column(
        result,
        ("Architecture",),
        required=True,
    )

    seed_column = find_column(
        result,
        ("Seed",),
        required=False,
    )

    if seed_column is None:
        raise ValueError(
            "A run/seed column is required for run-level statistical analysis."
        )

    return result


def validate_long_results(
    dataframe: pd.DataFrame,
    metrics: Sequence[str] = DEFAULT_METRICS,
) -> pd.DataFrame:
    """
    Validate and clean the long-format run-level result table.

    No aggregation is performed here.
    """
    data = standardise_result_columns(
        dataframe
    )

    required_design = (
        "Dataset",
        "Representation",
        "Architecture",
        "Seed",
    )

    for column in required_design:
        if column not in data.columns:
            raise ValueError(
                f"Missing required experimental-design column: {column}"
            )

    available_metrics = [
        metric
        for metric in metrics
        if metric in data.columns
    ]

    if not available_metrics:
        raise ValueError(
            "None of the requested metric columns were found. "
            f"Requested: {list(metrics)}"
        )

    for column in required_design:
        if data[column].isna().any():
            raise ValueError(
                f"Missing values found in design column '{column}'."
            )

    for metric in available_metrics:
        data[metric] = pd.to_numeric(
            data[metric],
            errors="coerce",
        )

    if data[available_metrics].isna().any().any():
        bad_columns = [
            metric
            for metric in available_metrics
            if data[metric].isna().any()
        ]
        raise ValueError(
            "Non-numeric or missing metric values found in: "
            f"{bad_columns}"
        )

    return data


def validate_factorial_completeness(
    dataframe: pd.DataFrame,
    expected_datasets: Sequence[str] = DEFAULT_DATASETS,
    expected_representations: Sequence[str] = DEFAULT_REPRESENTATIONS,
    expected_architectures: Sequence[str] = DEFAULT_ARCHITECTURES,
    expected_seeds: Sequence[int] = DEFAULT_SEEDS,
) -> pd.DataFrame:
    """
    Report missing Dataset × Representation × Architecture × Seed cells.

    The function returns a table rather than raising immediately so that
    incomplete historical result collections can be inspected explicitly.
    """
    data = dataframe

    expected = pd.MultiIndex.from_product(
        [
            expected_datasets,
            expected_representations,
            expected_architectures,
            expected_seeds,
        ],
        names=[
            "Dataset",
            "Representation",
            "Architecture",
            "Seed",
        ],
    )

    observed = (
        data[
            [
                "Dataset",
                "Representation",
                "Architecture",
                "Seed",
            ]
        ]
        .drop_duplicates()
        .set_index(
            [
                "Dataset",
                "Representation",
                "Architecture",
                "Seed",
            ]
        )
        .index
    )

    missing = expected.difference(
        observed
    )

    return missing.to_frame(
        index=False
    )


def descriptive_statistics(
    dataframe: pd.DataFrame,
    metric: str,
    group_by: Sequence[str] = (
        "Dataset",
        "Representation",
        "Architecture",
    ),
) -> pd.DataFrame:
    """
    Calculate run-level descriptive statistics.

    Returns:
        n
        mean
        sd
        standard_error
        ci95_lower
        ci95_upper
        min
        max

    The confidence interval is the two-sided 95% t interval for the mean.
    """
    if metric not in dataframe.columns:
        raise ValueError(
            f"Metric '{metric}' is not present."
        )

    rows = []

    grouped = dataframe.groupby(
        list(group_by),
        dropna=False,
    )

    for keys, group in grouped:
        if not isinstance(keys, tuple):
            keys = (keys,)

        values = pd.to_numeric(
            group[metric],
            errors="coerce",
        ).dropna().to_numpy(
            dtype=float
        )

        n = len(values)

        if n == 0:
            continue

        mean = float(
            np.mean(values)
        )

        if n > 1:
            sd = float(
                np.std(
                    values,
                    ddof=1,
                )
            )
            se = sd / math.sqrt(n)

            t_critical = t_critical_95(
                n - 1
            )

            margin = t_critical * se

            ci_lower = mean - margin
            ci_upper = mean + margin

        else:
            sd = float("nan")
            se = float("nan")
            ci_lower = float("nan")
            ci_upper = float("nan")

        row = {
            column: value
            for column, value in zip(
                group_by,
                keys,
            )
        }

        row.update(
            {
                "Metric": metric,
                "n": n,
                "mean": mean,
                "sd": sd,
                "standard_error": se,
                "ci95_lower": ci_lower,
                "ci95_upper": ci_upper,
                "min": float(np.min(values)),
                "max": float(np.max(values)),
            }
        )

        rows.append(row)

    return pd.DataFrame(rows)


def t_critical_95(
    degrees_of_freedom: int,
) -> float:
    """
    Return the two-sided 95% Student-t critical value.

    scipy.stats.t is used when available. A normal approximation is used only
    as a transparent fallback for environments where SciPy is unavailable.
    """
    if degrees_of_freedom <= 0:
        raise ValueError(
            "Degrees of freedom must be positive."
        )

    try:
        from scipy.stats import t

        return float(
            t.ppf(
                0.975,
                degrees_of_freedom,
            )
        )

    except ImportError:
        # Transparent fallback for large-df approximation.
        # This is not used in the intended SciPy-based repository environment.
        return 1.959963984540054


def compute_partial_eta_squared(
    anova_table: pd.DataFrame,
) -> pd.DataFrame:
    """
    Add partial eta-squared to a Type III ANOVA table.

    For each tested effect:

        partial eta^2 = SS_effect /
                        (SS_effect + SS_error)

    Residual and non-numeric rows receive NaN.
    """
    table = anova_table.copy()

    if "sum_sq" not in table.columns:
        raise ValueError(
            "ANOVA table must contain 'sum_sq'."
        )

    residual_name = "Residual"

    if residual_name not in table.index:
        residual_candidates = [
            index
            for index in table.index
            if str(index).lower() == "residual"
        ]

        if not residual_candidates:
            raise ValueError(
                "Residual row was not found in the ANOVA table."
            )

        residual_name = residual_candidates[0]

    ss_error = float(
        table.loc[
            residual_name,
            "sum_sq",
        ]
    )

    values = []

    for index, row in table.iterrows():
        if index == residual_name:
            values.append(np.nan)
            continue

        ss_effect = pd.to_numeric(
            row["sum_sq"],
            errors="coerce",
        )

        if pd.isna(ss_effect):
            values.append(np.nan)
        else:
            denominator = ss_effect + ss_error

            if denominator <= 0:
                values.append(np.nan)
            else:
                values.append(
                    float(
                        ss_effect / denominator
                    )
                )

    table["partial_eta_squared"] = values

    return table


def factorial_anova(
    dataframe: pd.DataFrame,
    metric: str,
    include_three_way: bool = True,
) -> pd.DataFrame:
    """
    Run the documented full-factorial Type III ANOVA.

    Model:

        metric ~ C(Dataset) * C(Representation) * C(Architecture)

    The Run/Seed is retained as the repeated experimental observation unit;
    each row therefore corresponds to one run-level condition.

    Sum-to-zero contrasts are used for Type III tests.
    """
    if metric not in dataframe.columns:
        raise ValueError(
            f"Metric '{metric}' is not present."
        )

    try:
        import statsmodels.api as sm
        import statsmodels.formula.api as smf
        from patsy.contrasts import Sum

    except ImportError as exc:
        raise ImportError(
            "statsmodels and patsy are required for factorial ANOVA. "
            "Install them with: pip install statsmodels patsy"
        ) from exc

    data = dataframe[
        [
            "Dataset",
            "Representation",
            "Architecture",
            metric,
        ]
    ].dropna().copy()

    if include_three_way:
        formula = (
            f"{metric} ~ "
            "C(Dataset, Sum) * "
            "C(Representation, Sum) * "
            "C(Architecture, Sum)"
        )
    else:
        formula = (
            f"{metric} ~ "
            "C(Dataset, Sum) * "
            "C(Representation, Sum) + "
            "C(Architecture, Sum)"
        )

    model = smf.ols(
        formula=formula,
        data=data,
    ).fit()

    table = sm.stats.anova_lm(
        model,
        typ=3,
    )

    table = compute_partial_eta_squared(
        table
    )

    table.attrs["metric"] = metric
    table.attrs["formula"] = formula
    table.attrs["n_observations"] = len(data)

    return table


def extract_interaction_effect(
    anova_table: pd.DataFrame,
    interaction: str = (
        "C(Representation, Sum):C(Architecture, Sum)"
    ),
) -> pd.Series:
    """
    Extract the Representation × Architecture inferential term.

    The function searches both the exact Type III term and a readable
    substring, making it robust to statsmodels term formatting.
    """
    if interaction in anova_table.index:
        return anova_table.loc[
            interaction
        ]

    candidates = [
        index
        for index in anova_table.index
        if (
            "Representation" in str(index)
            and "Architecture" in str(index)
            and "Dataset" not in str(index)
        )
    ]

    if len(candidates) != 1:
        raise ValueError(
            "Could not uniquely identify the "
            "Representation × Architecture interaction. "
            f"Candidates: {candidates}"
        )

    return anova_table.loc[
        candidates[0]
    ]


def dataset_specific_anova(
    dataframe: pd.DataFrame,
    metric: str,
) -> dict[str, pd.DataFrame]:
    """
    Run Representation × Architecture Type III ANOVA separately for each
    dataset.

    Model:

        metric ~ C(Representation, Sum) * C(Architecture, Sum)
    """
    try:
        import statsmodels.api as sm
        import statsmodels.formula.api as smf

    except ImportError as exc:
        raise ImportError(
            "statsmodels is required for ANOVA."
        ) from exc

    results = {}

    for dataset, subset in dataframe.groupby(
        "Dataset",
        sort=True,
    ):
        subset = subset[
            [
                "Representation",
                "Architecture",
                metric,
            ]
        ].dropna()

        formula = (
            f"{metric} ~ "
            "C(Representation, Sum) * "
            "C(Architecture, Sum)"
        )

        model = smf.ols(
            formula=formula,
            data=subset,
        ).fit()

        table = sm.stats.anova_lm(
            model,
            typ=3,
        )

        table = compute_partial_eta_squared(
            table
        )

        table.attrs["dataset"] = dataset
        table.attrs["metric"] = metric
        table.attrs["formula"] = formula

        results[str(dataset)] = table

    return results


def save_anova_table(
    table: pd.DataFrame,
    path: str | Path,
) -> None:
    """Save an ANOVA table as CSV."""
    path = Path(path)
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    table.to_csv(
        path,
        index=True,
    )


def save_descriptive_table(
    table: pd.DataFrame,
    path: str | Path,
) -> None:
    """Save descriptive statistics as CSV."""
    path = Path(path)
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    table.to_csv(
        path,
        index=False,
    )


def analyse_metric(
    dataframe: pd.DataFrame,
    metric: str,
    output_dir: Optional[str | Path] = None,
    include_three_way: bool = True,
) -> dict:
    """
    Run the standard statistical analysis for one metric.

    Outputs:
        * Dataset × Representation × Architecture descriptives
        * full factorial Type III ANOVA
        * extracted Representation × Architecture interaction
        * dataset-specific ANOVA tables
    """
    data = validate_long_results(
        dataframe,
        metrics=(metric,),
    )

    descriptives = descriptive_statistics(
        data,
        metric=metric,
    )

    anova = factorial_anova(
        data,
        metric=metric,
        include_three_way=include_three_way,
    )

    interaction = extract_interaction_effect(
        anova
    )

    dataset_anova = dataset_specific_anova(
        data,
        metric=metric,
    )

    if output_dir is not None:
        output_dir = Path(output_dir)
        output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        safe_metric = (
            metric.lower()
            .replace(" ", "_")
            .replace("-", "_")
        )

        save_descriptive_table(
            descriptives,
            output_dir
            / f"{safe_metric}_descriptive_statistics.csv",
        )

        save_anova_table(
            anova,
            output_dir
            / f"{safe_metric}_factorial_anova.csv",
        )

        interaction.to_frame().T.to_csv(
            output_dir
            / f"{safe_metric}_representation_architecture_interaction.csv",
            index=True,
        )

        dataset_dir = (
            output_dir
            / f"{safe_metric}_dataset_specific"
        )
        dataset_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        for dataset, table in dataset_anova.items():
            filename = (
                str(dataset)
                .replace("/", "_")
                .replace("\\", "_")
                .replace(" ", "_")
                + ".csv"
            )

            save_anova_table(
                table,
                dataset_dir / filename,
            )

    return {
        "descriptive_statistics": descriptives,
        "factorial_anova": anova,
        "representation_architecture_interaction": interaction,
        "dataset_specific_anova": dataset_anova,
    }


def analyse_results_file(
    results_path: str | Path,
    output_dir: Optional[str | Path] = None,
    metrics: Iterable[str] = DEFAULT_METRICS,
    include_three_way: bool = True,
) -> dict[str, dict]:
    """
    Load a long-format result CSV and analyse all available requested metrics.
    """
    results_path = Path(results_path)

    if not results_path.exists():
        raise FileNotFoundError(
            f"Results file not found: {results_path}"
        )

    raw = pd.read_csv(
        results_path
    )

    data = standardise_result_columns(
        raw
    )

    outputs = {}

    for metric in metrics:
        if metric not in data.columns:
            continue

        outputs[metric] = analyse_metric(
            data,
            metric=metric,
            output_dir=output_dir,
            include_three_way=include_three_way,
        )

    if not outputs:
        raise ValueError(
            "None of the requested metrics were found in the result file."
        )

    return outputs


def build_argument_parser() -> argparse.ArgumentParser:
    """Create the command-line interface."""
    parser = argparse.ArgumentParser(
        description=(
            "Run descriptive and factorial statistical analyses "
            "on run-level IDS results."
        )
    )

    parser.add_argument(
        "--results",
        type=Path,
        required=True,
        help="Run-level result CSV.",
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(
            "results/statistical_analysis"
        ),
        help="Directory for statistical-analysis CSV outputs.",
    )

    parser.add_argument(
        "--metrics",
        type=str,
        default=",".join(DEFAULT_METRICS),
        help=(
            "Comma-separated metrics to analyse. "
            "Example: Macro_F1,MCC"
        ),
    )

    parser.add_argument(
        "--no-three-way",
        action="store_true",
        help=(
            "Omit the Dataset × Representation × Architecture "
            "three-way term from the full factorial model."
        ),
    )

    return parser


def main() -> None:
    """Command-line entry point."""
    parser = build_argument_parser()
    args = parser.parse_args()

    metrics = tuple(
        metric.strip()
        for metric in args.metrics.split(",")
        if metric.strip()
    )

    outputs = analyse_results_file(
        results_path=args.results,
        output_dir=args.output_dir,
        metrics=metrics,
        include_three_way=not args.no_three_way,
    )

    print(
        f"Analysed {len(outputs)} metric(s)."
    )

    for metric, result in outputs.items():
        interaction = result[
            "representation_architecture_interaction"
        ]

        print(
            f"\n{metric}"
        )
        print(
            interaction.to_string()
        )


def _self_check() -> None:
    """
    Lightweight internal validation of the descriptive-analysis utilities.

    The synthetic data are used only to verify calculations and do not
    represent manuscript results.
    """
    rows = []

    for dataset in (
        "CIC-DDoS2019",
        "CICIoT2023",
        "CIC-IoT-DIAD2024",
    ):
        for representation in (
            "Flow",
            "Header",
            "Hybrid",
        ):
            for architecture in (
                "LR",
                "RF",
                "XGB",
                "CNN",
                "BiLSTM",
            ):
                for seed in (
                    2026,
                    2027,
                    2028,
                ):
                    offset = (
                        0.001 * (seed - 2026)
                        + 0.002
                        * (
                            list(
                                (
                                    "Flow",
                                    "Header",
                                    "Hybrid",
                                )
                            ).index(
                                representation
                            )
                        )
                    )

                    rows.append(
                        {
                            "Dataset": dataset,
                            "Representation": representation,
                            "Architecture": architecture,
                            "Seed": seed,
                            "Macro_F1": 0.90 + offset,
                            "MCC": 0.85 + offset,
                        }
                    )

    data = pd.DataFrame(rows)

    validated = validate_long_results(
        data,
        metrics=("Macro_F1", "MCC"),
    )

    assert len(validated) == len(rows)

    desc = descriptive_statistics(
        validated,
        metric="Macro_F1",
    )

    assert len(desc) == 45

    missing = validate_factorial_completeness(
        validated,
        expected_seeds=(2026, 2027, 2028),
    )

    assert missing.empty

    print(
        "statistical_analysis.py self-check passed."
    )


if __name__ == "__main__":
    main()
